auditor:
  provider: '${AUDITOR_PROVIDER}'
  endpoint: '${AUDITOR_ENDPOINT}'


auth_proxy:
  oauth:
    client: '${OAUTH_CLIENT_ID}'
    secret: '${OAUTH_CLIENT_SECRET}'
    provider: '${OAUTH_PROVIDER}'
  session:
    secret: '${SESSION_SECRET}'
  extra:
    emails: './allow.emails'


gateway:
  domain: '${GATEWAY_DOMAIN}'


http_proxy:
  bind:
    port: 443
  tls:
    crt_file: /vol/certs/server.crt
    key_file: /vol/certs/server.key


# Apps are added here by the entrypoint from ${APPS_FILE}
