version: '3.0'


services:
  mongo:
    image: "mongo:3.4.7"

  auditstore:
    build:
      context: .
      dockerfile: Dockerfile-auditstore
    links:
      - mongo
    ports:
      - '8092:8092'

  authgateway:
    build:
      context: ../../
    environment:
      - 'ALLOWED_EMAILS=a1@b.c,a2@b.c'
      - 'AUDITOR_PROVIDER=http'
      - 'AUDITOR_ENDPOINT=http://auditstore:8092/audit'
      - 'OAUTH_PROVIDER=github'
      - 'OAUTH_CLIENT_ID=...'
      - 'OAUTH_CLIENT_SECRET=...'
      - 'SESSION_SECRET=MDEyMzQ1Njc4OTAxMjM0NQ=='
    links:
      - auditstore
    ports:
      - '8443:443'
    volumes:
      - '../../:/vol/certs'
