version: '3.0'


services:
  mongo:
    image: "mongo:3.4.7"

  auditstore:
    build:
      context: .
      dockerfile: Dockerfile-auditstore
    command:
      - 'python'
      - 'main.py'
      - '--debug'
      - '--config'
      - '/auditstore/config.py'
    links:
      - mongo
    ports:
      - '8092:8092'
